# <font color=darkblue> Machine Learning model deployment with Flask framework</font>

## <font color=Blue>Used Cars Price Prediction Application</font>

### Objective:
1. To build a Machine learning regression model to predict the selling price of the used cars based on the different input features like fuel_type, kms_driven, type of transmission etc.
2. Deploy the machine learning model with the help of the flask framework.

### Dataset Information:
#### Dataset Source: https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho?select=CAR+DETAILS+FROM+CAR+DEKHO.csv
This dataset contains information about used cars listed on www.cardekho.com
- **Car_Name**: Name of the car
- **Year**: Year of Purchase
- **Selling Price (target)**: Selling price of the car in lakhs
- **Present Price**: Present price of the car in lakhs
- **Kms_Driven**: kilometers driven
- **Fuel_Type**: Petrol/diesel/CNG
- **Seller_Type**: Dealer or Indiviual
- **Transmission**: Manual or Automatic
- **Owner**: first, second or third owner


### 1. Import required libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib.inline

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder


UsageError: Line magic function `%matplotlib.inline` not found.


### 2. Load the dataset

In [ ]:
import os
os.getcwd()

In [ ]:
#1 Load the dataset
df = pd.read_csv("car+data.csv")
df.head()

### 3. Check the shape and basic information of the dataset.

In [ ]:
df.shape

In [ ]:
df.info()

### 4. Check for the presence of the duplicate records in the dataset? If present drop them

In [ ]:
df[df.duplicated()]

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df[df.duplicated()]

In [ ]:
df.shape

### 5. Drop the columns which you think redundant for the analysis.

In [8]:
df = pd.read_csv("car+data.csv")
df.drop('Car_Name',  axis=1, inplace=True)





### 6. Extract a new feature called 'age_of_the_car' from the feature 'year' and drop the feature year

In [10]:
df['age_of_the_car']=2024-df['Year']

In [11]:
df.drop('Year', axis=1, inplace=True)

In [12]:
df.head(2)

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   

  Transmission  Owner  age_of_the_car  
0       Manual      0              10  
1       Manual      0              11

In [14]:
import datetime
datetime.date.today().year

2024

### 7. Encode the categorical columns

In [15]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [17]:
df['Seller_Type'].unique()

array(['Dealer', 'Individual'], dtype=object)

In [16]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [27]:
#Manual encoding
df['Fuel_Type'] = df['Fuel_Type'].replace({'Petrol': 0 ,'Diesel': 1 ,'CNG':2})
df['Seller_Type'] = df['Seller_Type'].replace({'Dealer' : 0 ,'Individual': 1})
df['Transmission'] = df['Transmission'].replace({'Manual' : 0,'Automatic' : 1})

In [28]:
df['Fuel_Type'].unique()

array([0, 1, 2], dtype=int64)

In [29]:
df['Seller_Type'].unique()

array([0, 1], dtype=int64)

In [30]:
df['Transmission'].unique()

array([0, 1], dtype=int64)

In [31]:
df.head(2)

Selling_Price  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  \
0           3.35           5.59       27000          0            0   
1           4.75           9.54       43000          1            0   

   Transmission  Owner  age_of_the_car  
0             0      0              10  
1             0      0              11

### 8. Separate the target and independent features.

In [33]:
X = df.drop('Selling_Price', axis=1)
y = df['Selling_Price']


### 9. Split the data into train and test.

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(210, 7) (91, 7)
(210,) (91,)


### 10. Build a Random forest Regressor model and check the r2-score for train and test.

In [42]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
rf.fit(X_train, y_train)



RandomForestRegressor()

In [41]:
from sklearn.metrics import r2_score


y_train_preds = rf.predict(X_train)
y_test_preds = rf.predict(X_test)

r2_train=r2_score( y_train,y_train_preds)
r2_test=r2_score( y_test,y_test_preds)

print(r2_train)
print(r2_test)

0.987761133469859
0.9122167061115241


### 11. Create a pickle file with an extension as .pkl

In [43]:
import  pickle 
pickle.dump(rf,open('model.pkl', 'wb'))


IndentationError: unexpected indent (678971410.py, line 2)

### 12. Create new folder/new project in visual studio/pycharm that should contain the "model.pkl" file *make sure you are using a virutal environment and install required packages.*

### a) Create a basic HTML form for the frontend

Create a file **index.html** in the templates folder and copy the following code.

In [47]:
<!DOCTYPE html>

<html lang="en">




<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Used Car Selling Price Prediction</title>

</head>




<body>




    <div class="hero-image">

      <div class="hero-text">




        <h1 style="font-size:50px">Used Car Price Predictor</h1>

         <br><br><h3>{{ prediction_text }}<h3>

      </div>

    </div>




     <style>




        body, html {

          height: 100%;

          margin: 0;

          font-family: Arial, Helvetica, sans-serif;

        }




        .hero-image {

          background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('/static/bg_image.jpg');

          height: 50%;

          background-position: bottom;

          background-repeat: no-repeat;

          background-size: cover;

          position: relative;

        }




        .hero-text {

          text-align: center;

          position: absolute;

          top: 50%;

          left: 50%;

          transform: translate(-50%, -50%);

          color: white;

        }




    </style>







    <div style="color:	rgb(0, 0, 0)">

        <form action="{{ url_for('predict')}}" method="post">

            <h2>Enter Car Details: </h2>

            <h3>Age of the car(In years)</h3>

            <input id="first" name="Age_of_the_car" type="number ">

            <h3>Present Showroom Price(In lakhs)</h3><input id="second" name="Present_Price" required="required">

            <h3>Kilometers Driven</h3><input id="third" name="Kms_Driven" required="required">

            <h3>Owner Type (0/1/3)</h3><input id="fourth" name="Owner" required="required">

            <h3>Fuel type</h3><select name="Fuel_Type" id="fuel" required="required">

                <option value="0">Petrol</option>

                <option value="1">Diesel</option>

                <option value="2">CNG</option>

            </select>

            <h3>Seller Type</h3><select name="Seller_Type" id="resea" required="required">

                <option value="0">Dealer</option>

                <option value="1">Individual</option>

            </select>

            <h3>Transmission type</h3><select name="Transmission" id="research" required="required">

                <option value="0">Manual Car</option>

                <option value="1">Automatic Car</option>

            </select>

            <br><br><button id="sub" type="submit ">Predict Selling Price</button>

            <br>







        </form>




    </div>




    <style>

	body {

            background-color: 101, 10, 20;

            text-align: center;

            padding: 0px;

	    font-family: Helvetica;

        }




        #research {

            font-size: 18px;

            width: 200px;

            height: 23px;

            top: 23px;

        }




        #box {

            border-radius: 60px;

            border-color: 45px;

            border-style: solid;

            text-align: center;

            background-color: white;

            font-size: medium;

            position: absolute;

            width: 700px;

            bottom: 9%;

            height: 850px;

            right: 30%;

            padding: 0px;

            margin: 0px;

            font-size: 14px;

        }




        #fuel {

            width: 83px;

            height: 43px;

            text-align: center;

            border-radius: 14px;

            font-size: 20px;

        }




        #fuel:hover {

            background-color: white;

        }




        #research {

            width: 150px;

            height: 43px;

            text-align: center;

            border-radius: 14px;

            font-size: 18px;

        }




        #research:hover {

            background-color: white;

        }




        #resea {

            width: 99px;

            height: 43px;

            text-align: center;

            border-radius: 14px;

            font-size: 18px;

        }




        #resea:hover {

            background-color: white;

        }




        #sub {

            background-color: Green;

            font-family:'Helvetica' monospace;

            font-weight: bold;

            width: 180px;

            height: 60px;

            text-align: center;

            border-radius: 20px;

            font-size: 18px;

            color: white;

        }




        #sub:hover {

            background-color: white;

        }




        #first {

            border-radius: 14px;

            height: 25px;

            font-size: 20px;

            text-align: center;

        }




        #second {

            border-radius: 14px;

            height: 25px;

            font-size: 20px;

            text-align: center;

        }




        #third {

            border-radius: 14px;

            height: 25px;

            font-size: 20px;

            text-align: center;

        }




        #fourth {

            border-radius: 14px;

            height: 25px;

            font-size: 20px;

            text-align: center;

        }

    </style>

</body>




</html>

SyntaxError: invalid syntax (3425318590.py, line 1)

### b) Create app.py file and write the predict function

In [51]:
from flask import Flask, render_template, request
import pickle
import numpy as np

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    with open('model.pkl', 'rb') as f:
        model, label_encoders = pickle.load(f)
    
    age = int(request.form['age'])
    kms = float(request.form['kms'])
    fuel = request.form['fuel']
    seller = request.form['seller']
    transmission = request.form['transmission']
    
    fuel_encoded = label_encoders['Fuel_Type'].transform([fuel])[0]
    seller_encoded = label_encoders['Seller_Type'].transform([seller])[0]
    transmission_encoded = label_encoders['Transmission'].transform([transmission])[0]
    
    input_data = np.array([[age, kms, fuel_encoded, seller_encoded, transmission_encoded]])
    prediction = model.predict(input_data)[0]
    
    return f'Predicted Selling Price: {prediction} lakhs'

if __name__ == '__main__':
    app.run(debug=True)


 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with watchdog (windowsapi)


SystemExit: 1

### 13. Run the app.py python file which will render to index html page then enter the input values and get the prediction.

### Happy Learning :)